sonar.organization=My Candys
sonar.projectKey=sonar-doces
sonar.projectName=API My Candys - Node.js

# Configuração de arquivos fonte
sonar.sources=.
sonar.encoding=UTF-8

# Pastas e arquivos a serem ignorados pelo scanner
sonar.exclusions=**/node_modules/**, **/*.spec.js, **/dist/**, **/coverage/**